using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DemoCSharp._3
{
    /*
     * A class without a name is generated and assigned to an implicitly typed local variable.
     * For anonymous type syntax, the compiler generates a class.
     * Properties of the class generated by the complier are value and data type given in the declaration.
     * Intellisense supports anonymous type class properties. 
     * Properties of one anonymous type can be used in the declaration of other anonymous types.
     */
    public class AnonymousTypes
    {
        public void test()
        {
            var MyAnonClass = new
                {
                    Name = "Ranjeet",
                    Subject = "ASP.Net"
                };

            Console.WriteLine(MyAnonClass.Name);
            Console.Read();

            var SecondAnoynClass = new
            {
                info = MyAnonClass.Name + MyAnonClass.Subject
            };
            Console.WriteLine(SecondAnoynClass.info);
            Console.Read();
        }
    }
}
